<a href="https://colab.research.google.com/github/nsgrn/Python-Intro-Assignment/blob/main/Numpy_HomeWork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [11]:
import numpy as np
houses = ["H_1", "H_2", "H_3", "H_4", "H_5", "H_6", "H_7", "H_8", "H_9", "H_10" ]
house_sizes = [60, 75, 83, 91, 87, 76, 45, 33, 54, 101]
num_of_rooms = [12, 8, 9, 1, 3, 4, 7, 3, 2, 6]
house_prices = [110, 200, 800, 600, 750, 1300, 320, 6660, 765, 12300]
house_features = np.array([houses, house_sizes, num_of_rooms, house_prices])
print(house_features)

[['H_1' 'H_2' 'H_3' 'H_4' 'H_5' 'H_6' 'H_7' 'H_8' 'H_9' 'H_10']
 ['60' '75' '83' '91' '87' '76' '45' '33' '54' '101']
 ['12' '8' '9' '1' '3' '4' '7' '3' '2' '6']
 ['110' '200' '800' '600' '750' '1300' '320' '6660' '765' '12300']]


In [12]:
house_features[1][0] = 32
print(house_features)

[['H_1' 'H_2' 'H_3' 'H_4' 'H_5' 'H_6' 'H_7' 'H_8' 'H_9' 'H_10']
 ['32' '75' '83' '91' '87' '76' '45' '33' '54' '101']
 ['12' '8' '9' '1' '3' '4' '7' '3' '2' '6']
 ['110' '200' '800' '600' '750' '1300' '320' '6660' '765' '12300']]


In [13]:
house_features[0][0] = "first_H"
print(house_features)

[['first_H' 'H_2' 'H_3' 'H_4' 'H_5' 'H_6' 'H_7' 'H_8' 'H_9' 'H_10']
 ['32' '75' '83' '91' '87' '76' '45' '33' '54' '101']
 ['12' '8' '9' '1' '3' '4' '7' '3' '2' '6']
 ['110' '200' '800' '600' '750' '1300' '320' '6660' '765' '12300']]


#3- Display the shape of the array and explain what it means. This means 4 rows 10 columns

In [14]:
print(house_features.shape)

(4, 10)


In [8]:
print(house_features.reshape(2,20))

[['first_H' 'H_2' 'H_3' 'H_4' 'H_5' 'H_6' 'H_7' 'H_8' 'H_9' 'H_10' '32'
  '75' '83' '91' '87' '76' '45' '33' '54' '101']
 ['12' '8' '9' '1' '3' '4' '7' '3' '2' '6' '110' '200' '800' '600' '750'
  '1300' '320' '6660' '765' '12300']]


#2- Transpose the array you have created, so that every line can represent features of one house.

In [15]:
print(house_features.T)

[['first_H' '32' '12' '110']
 ['H_2' '75' '8' '200']
 ['H_3' '83' '9' '800']
 ['H_4' '91' '1' '600']
 ['H_5' '87' '3' '750']
 ['H_6' '76' '4' '1300']
 ['H_7' '45' '7' '320']
 ['H_8' '33' '3' '6660']
 ['H_9' '54' '2' '765']
 ['H_10' '101' '6' '12300']]


#4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.


In [17]:
import pandas as pd
my_dataset = pd.read_csv("earthquakes1970-2014.csv")
print(my_dataset)

                    DateTime  Latitude  Longitude   Depth  Magnitude MagType  \
0     1970/01/04 17:00:40.20   24.1390   102.5030   31.00        7.5      Ms   
1     1970/01/06 05:35:51.80   -9.6280   151.4580    8.00        6.2      Ms   
2     1970/01/08 17:12:39.10  -34.7410   178.5680  179.00        6.1      Mb   
3     1970/01/10 12:07:08.60    6.8250   126.7370   73.00        6.1      Mb   
4     1970/01/16 08:05:39.00   60.2800  -152.6600   85.00        6.0      ML   
...                      ...       ...        ...     ...        ...     ...   
5299  2013/12/01 06:29:57.80    2.0440    96.8261   20.00        6.0      Mw   
5300  2013/12/08 17:24:54.20   44.4438   149.1667   28.00        6.1      Mw   
5301  2013/12/17 23:38:08.10   20.7635   146.7599   16.06        6.2      Mw   
5302  2014/01/01 16:03:28.89  -13.8779   167.2434  187.00        6.5      Mw   
5303  2014/01/13 04:01:04.69   19.0014   -66.8478   28.00        6.4      Mw   

      NbStations   Gap  Distance   RMS 

In [18]:
import numpy as np
data_array = my_dataset.to_numpy()
print(data_array)

[['1970/01/04 17:00:40.20' 24.1389999999999 102.503 ... 0.0 'NEI'
  1970010440.0]
 ['1970/01/06 05:35:51.80' -9.628 151.458 ... 0.0 'NEI' 1970010640.0]
 ['1970/01/08 17:12:39.10' -34.741 178.568 ... 0.0 'NEI' 1970010840.0]
 ...
 ['2013/12/17 23:38:08.10' 20.7635 146.759899999999 ... 0.74 'us'
  2013121720.0]
 ['2014/01/01 16:03:28.89' -13.8779 167.2434 ... 0.67 'us' 2014010120.0]
 ['2014/01/13 04:01:04.69' 19.0014 -66.8478 ... 1.42 'us' 2014011320.0]]


#5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [19]:
new_array = data_array[:20, [2, 4, 5, 6, 11]]
new_array

array([[102.503, 7.5, 'Ms', 90.0, 1970010440.0],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-152.66, 6.0, 'ML', 0.0, nan],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [-179.5898, 6.0, 'ML', 0.0, nan],
       [-175.039999999999, 6.1, 'ML', 0.0, nan],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-153.97, 6.5, 'ML', 0.0, nan],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 197003154

In [20]:
sliced_data = my_dataset.iloc[:20, [2, 4, 5, 6, 11]]
sliced_data

Longitude  Magnitude MagType  NbStations       EventID
0    102.5030        7.5      Ms        90.0  1.970010e+09
1    151.4580        6.2      Ms        85.0  1.970011e+09
2    178.5680        6.1      Mb        59.0  1.970011e+09
3    126.7370        6.1      Mb        91.0  1.970011e+09
4   -152.6600        6.0      ML         0.0           NaN
5   -177.3490        6.5      Mb       175.0  1.970012e+09
6    142.9660        6.4      Ms       199.0  1.970012e+09
7   -104.2980        6.6      Ms       140.0  1.970012e+09
8    166.3700        6.4      Ms        91.0  1.970013e+09
9    -99.4840        6.5      Ms       100.0  1.970020e+09
10   122.1170        6.6      Ms        94.0  1.970021e+09
11   100.7750        6.1      Ms        57.0  1.970021e+09
12   103.0310        6.0      Ms        94.0  1.970022e+09
13  -179.5898        6.0      ML         0.0           NaN
14  -175.0400        6.1      ML         0.0           NaN
15   143.7070        6.2      Ms        82.0  1.970030e+09
16   168.6030        6.5      Ms        61.0  1.970031e+09
17   148.8700        6.0      Mb        65.0  1.970031e+09
18  -153.9700        6.5      ML         0.0           NaN
19   -69.4990        6.0      Mb       118.0  1.970032e+09

#6- Display the row numbers where last values are equal to 4.5 or higher.



In [21]:
row_indices = np.where(new_array[:, -1] >= 4.5)[0]
print(row_indices)

[ 0  1  2  3  5  6  7  8  9 10 11 12 15 16 17 19]


<ipython-input-21-1ce00444b75f>:1: RuntimeWarning: invalid value encountered in greater_equal
  row_indices = np.where(new_array[:, -1] >= 4.5)[0]


In [22]:
indexin_pands = sliced_data.index[sliced_data.iloc[:, -1] >= 4.5]
print(list(indexin_pands))

[0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 19]


#7- Assign 1 to first row.



In [23]:
new_array[0, :] = 1
new_array

array([[1, 1, 1, 1, 1],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-152.66, 6.0, 'ML', 0.0, nan],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [-179.5898, 6.0, 'ML', 0.0, nan],
       [-175.039999999999, 6.1, 'ML', 0.0, nan],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-153.97, 6.5, 'ML', 0.0, nan],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 1970031540.0]], dtype=object)

#8- Save the final state of the array to disk. You are going to use this in the next assignment.



In [39]:
 np.save("final_array.npy", new_array)


#9- Load the array you saved in the previous lesson from the disk.



In [40]:
x_array = np.load("final_array.npy", allow_pickle=True)
x_array

array([[1, 1, 1, 1, 1],
       [151.458, 6.2, 'Ms', 85.0, 1970010640.0],
       [178.568, 6.1, 'Mb', 59.0, 1970010840.0],
       [126.736999999999, 6.1, 'Mb', 91.0, 1970011040.0],
       [-152.66, 6.0, 'ML', 0.0, nan],
       [-177.348999999999, 6.5, 'Mb', 175.0, 1970012040.0],
       [142.966, 6.4, 'Ms', 199.0, 1970012040.0],
       [-104.298, 6.6, 'Ms', 140.0, 1970012140.0],
       [166.37, 6.4, 'Ms', 91.0, 1970012640.0],
       [-99.48399999999991, 6.5, 'Ms', 100.0, 1970020440.0],
       [122.117, 6.6, 'Ms', 94.0, 1970020540.0],
       [100.775, 6.1, 'Ms', 57.0, 1970020640.0],
       [103.031, 6.0, 'Ms', 94.0, 1970022440.0],
       [-179.5898, 6.0, 'ML', 0.0, nan],
       [-175.039999999999, 6.1, 'ML', 0.0, nan],
       [143.706999999999, 6.2, 'Ms', 82.0, 1970030440.0],
       [168.603, 6.5, 'Ms', 61.0, 1970030940.0],
       [148.87, 6.0, 'Mb', 65.0, 1970031040.0],
       [-153.97, 6.5, 'ML', 0.0, nan],
       [-69.49899999999991, 6.0, 'Mb', 118.0, 1970031540.0]], dtype=object)

#10- Display the mean and the standard deviation for each column.



In [41]:
import numpy as np
def to_int(a):
    try:
        return int(a)
    except:
        return np.random.uniform(1, 10)
vectorized_func = np.vectorize(to_int)
array_clean = vectorized_func(x_array)
print(array_clean)

[[         1          1          1          1          1]
 [       151          6          8         85 1970010640]
 [       178          6          7         59 1970010840]
 [       126          6          4         91 1970011040]
 [      -152          6          2          0          5]
 [      -177          6          2        175 1970012040]
 [       142          6          1        199 1970012040]
 [      -104          6          5        140 1970012140]
 [       166          6          8         91 1970012640]
 [       -99          6          7        100 1970020440]
 [       122          6          5         94 1970020540]
 [       100          6          5         57 1970020640]
 [       103          6          3         94 1970022440]
 [      -179          6          9          0          4]
 [      -175          6          9          0          3]
 [       143          6          6         82 1970030440]
 [       168          6          4         61 1970030940]
 [       148  

In [46]:
C_means = np.mean(array_clean, axis=0)
C_stds = np.std(array_clean, axis=0)
print(C_means)
print(C_stds)

[2.20000000e+01 5.75000000e+00 5.00000000e+00 7.56000000e+01
 1.47751447e+09]
[1.37905402e+02 1.08972474e+00 2.64575131e+00 5.58134392e+01
 8.53043375e+08]


#11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)



In [47]:
values_to_substract = np.array([1, 25, 25, 10, 4])
result = array_clean.reshape(20,5) - values_to_substract
result

array([[         0,        -24,        -24,         -9,         -3],
       [       150,        -19,        -17,         75, 1970010636],
       [       177,        -19,        -18,         49, 1970010836],
       [       125,        -19,        -21,         81, 1970011036],
       [      -153,        -19,        -23,        -10,          1],
       [      -178,        -19,        -23,        165, 1970012036],
       [       141,        -19,        -24,        189, 1970012036],
       [      -105,        -19,        -20,        130, 1970012136],
       [       165,        -19,        -17,         81, 1970012636],
       [      -100,        -19,        -18,         90, 1970020436],
       [       121,        -19,        -20,         84, 1970020536],
       [        99,        -19,        -20,         47, 1970020636],
       [       102,        -19,        -22,         84, 1970022436],
       [      -180,        -19,        -16,        -10,          0],
       [      -176,        -19,   

#12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [48]:
array_clean = array_clean * 2
array_clean

array([[         2,          2,          2,          2,          2],
       [       302,         12,         16,        170, 3940021280],
       [       356,         12,         14,        118, 3940021680],
       [       252,         12,          8,        182, 3940022080],
       [      -304,         12,          4,          0,         10],
       [      -354,         12,          4,        350, 3940024080],
       [       284,         12,          2,        398, 3940024080],
       [      -208,         12,         10,        280, 3940024280],
       [       332,         12,         16,        182, 3940025280],
       [      -198,         12,         14,        200, 3940040880],
       [       244,         12,         10,        188, 3940041080],
       [       200,         12,         10,        114, 3940041280],
       [       206,         12,          6,        188, 3940044880],
       [      -358,         12,         18,          0,          8],
       [      -350,         12,   